safe: true
lsi: false
highlighter: rouge
markdown: kramdown
jekyll-redirect-from: true
plugins:
  - jekyll-redirect-from
  - octopress-escape-code
whitelist:
  - jekyll-redirect-from
escape_code: true
